#
# Your Crowdin credentials
#
project_id: 493199
api_token_env: CROWDIN_PERSONAL_TOKEN
# "base_path" : "."
# "base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
# https://support.crowdin.com/configuration-file/
#
files:
  # JSON translation files
  - source: /website/i18n/en/**/*
    translation: /website/i18n/%two_letters_code%/**/%original_file_name%
    ignore: [/website/i18n/en/docusaurus-plugin-content-blog]

  # Docs Markdown files
  - source: /website/docs/**/*
    translation: /website/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
