[versions]
kotlin = "1.5.31"
bukkit = "1.17.1"

[libraries]
hocon = "ninja.leaping.configurate:configurate-hocon:3.3"
kotlinx-serialization-hocon = "org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.3.0"

[plugins]
bukkitgradle = "ru.endlesscode.bukkitgradle:0.10.0"
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
