depend:
  - Mimic
  - CommandAPI
softdepend:
  - PlaceholderAPI
  - ProRPGItems # We want to use its ItemsRegistry.
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10
  - org.jetbrains.kotlinx:kotlinx-serialization-core:1.4.0
  - org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.4.0
  - com.zaxxer:HikariCP:5.0.1
permissions:
  ecinventory.open:
    default: true
  ecinventory.open.others:
    default: op
  ecinventory.reload:
    default: op
