depend:
  - Mimic
  - CommandAPI
softdepend:
  - PlaceholderAPI
  - ProRPGItems # We want to use its ItemsRegistry.
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10
  - org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.3.2
  - com.zaxxer:HikariCP:5.0.0
permissions:
  ecinventory.open:
    default: true
  ecinventory.open.others:
    default: op
  ecinventory.reload:
    default: op
