depend:
  - Mimic
  - CommandAPI
softdepend:
  - PlaceholderAPI
  - ProRPGItems # We want to use its ItemsRegistry.
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.20
  - org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.6.1
  - com.zaxxer:HikariCP:5.1.0
permissions:
  ecinventory.open:
    default: true
  ecinventory.open.others:
    default: op
  ecinventory.reload:
    default: op
